name: Update WAs and Release

on:
  push:
    branches:
      - release

jobs:
  update-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Latest Tag
      uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      
    - name: Increase Tag Version
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: "patch"

    - name: Print Params
      id: print-pararms
      run: |
        echo build_release = ${{ steps.commit.outputs.build_release }}
        echo tag = ${{ steps.get-latest-tag.outputs.tag }}
        echo new_version = ${{ steps.bump-semver.outputs.new_version }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:   
        tag_name: '${{ steps.bump-semver.outputs.new_version}}'
        release_name: 'Release v${{ steps.bump-semver.outputs.new_version }}'
        draft: false
        prerelease: false
        body: ${{ steps.read_commit_notes.outputs.commit_notes }}