name: Update WAs and Release

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main
  workflow_dispatch:



jobs:
  update-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Scripts/requirements.txt

    - name: Run updateWAs.py
      run: python Scripts/updateWAs.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Update WAs'
        git push
      continue-on-error: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v${{ github.run_number }}'
        release_name: 'Release ${{ github.run_number }}'
        draft: false
        prerelease: false
      if: success() && steps.commit.outputs.changes_detected == 'true'